version: "3"
services:
  queue:
    image: rabbitmq:3.7.2-management
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
      - queue_net
    restart: on-failure

  redis:
    image: redis:5.0.0
    ports:
      - "6379:6379"
    networks:
      - queue_net
    restart: on-failure

  recommedation_service:
    build: ./recommedation_service
    command: python3 recommendation_app.py
    depends_on:
      - queue
    networks:
      - queue_net
    restart: on-failure
    volumes:
      - ./data:/data


  parser:
    build: ./parser
    command: python3 parser.py
    depends_on:
      - queue
      - redis
    networks:
      - queue_net
    restart: on-failure
    volumes:
      - ./data:/data

#  crawler:
#    build: ./vk_crawler
#    command: python3 crawler.py
#    depends_on:
#      - queue
#    networks:
#      - queue_net
#    restart: on-failure

  web_server:
    build: ./web_server
    command: python3 web_server/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - queue
    networks:
      - queue_net
    restart: on-failure

  tg_bot:
    build: ./tg_bot
    command: python3 bot.py
    depends_on:
      - queue
    networks:
      - queue_net
    restart: on-failure

networks:
  queue_net:
    driver: bridge
